/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.user.dao;

import com.arangodb.springframework.annotation.Document;
import com.arangodb.springframework.annotation.Relations;
import org.kathra.core.model.User;
import org.kathra.core.model.User.*;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDb;
import java.util.List;

import org.kathra.resourcemanager.assignation.dao.AssignationDb;
import org.kathra.core.model.Resource.*;
import org.kathra.resourcemanager.user.dao.UserAssignationEdge;


/**
 * Entity class UserDb implementing db resource for class User
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-11-14T21:10:41.195Z
 * @author jboubechtoula
 */
@Document("Users")
public class UserDb extends AbstractResourceDb<User> {

		private String firstName; 
		private String lastName; 
		private String email; 
		private String password; 
		private String phone; 
		@Relations(edges = UserAssignationEdge.class, lazy = true) 
		private List<AssignationDb> groups; 


        public UserDb() {
        }
        public UserDb(String id) {
            super(id);
        }

		public String getFirstName() { return this.firstName;}
		public void setFirstName(String firstName) { this.firstName=firstName;}

		public String getLastName() { return this.lastName;}
		public void setLastName(String lastName) { this.lastName=lastName;}

		public String getEmail() { return this.email;}
		public void setEmail(String email) { this.email=email;}

		public String getPassword() { return this.password;}
		public void setPassword(String password) { this.password=password;}

		public String getPhone() { return this.phone;}
		public void setPhone(String phone) { this.phone=phone;}

		public List<AssignationDb> getGroups() { return this.groups;}
		public void setGroups(List<AssignationDb> groups) { this.groups=groups;}



}
