/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.binaryrepository.dao;

import com.arangodb.springframework.core.ArangoOperations;
import org.kathra.core.model.BinaryRepository;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDao;
import org.kathra.resourcemanager.resource.utils.LeanResourceDbUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.kathra.resourcemanager.resource.utils.EdgeUtils;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import fr.xebia.extras.selma.Selma;
import java.util.stream.Stream;

import org.kathra.resourcemanager.group.dao.GroupDb;
import org.kathra.resourcemanager.group.dao.GroupBinaryRepositoryEdge;
import org.kathra.resourcemanager.group.dao.GroupBinaryRepositoryEdgeRepository;


/**
 * Abtrasct dao service to manage BinaryRepository using BinaryRepositoryDb with ArangoRepository
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-27T00:08:51.143Z
 * @author Julien Boubechtoula
 */
public abstract class AbstractBinaryRepositoryDao extends AbstractResourceDao<BinaryRepository, BinaryRepositoryDb, String> {

	@Autowired
	GroupBinaryRepositoryEdgeRepository groupBinaryRepositoryEdgeRepository;


    public AbstractBinaryRepositoryDao(@Autowired BinaryRepositoryRepository repository, @Autowired ArangoOperations operations){
        super(repository, operations);
    }

    @PostConstruct
    public void initCollectionIfNotExist(){
        if(repository.count() == 0) {
            try {
                operations.insert(new BinaryRepositoryDb("init"));
                repository.deleteById("init");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
//init edge repositories 
		this.groupBinaryRepositoryEdgeRepository.count();

    }

    @Override
    public void create(BinaryRepository object, String author) throws Exception {
        super.create(object, author);
        updateReferences(object);
    }

    @Override
    public void update(BinaryRepository object, String author) throws Exception {
        super.update(object, author);
        updateReferences(object);
    }
    @Override
    public void delete(BinaryRepository object, String author) throws Exception {
        super.delete(object, author);
        updateReferences(object);
    }
    private void updateReferences(BinaryRepository object) throws Exception {
        BinaryRepositoryDb resourceDb = this.convertResourceToResourceDb(object);
        EdgeUtils.of(GroupBinaryRepositoryEdge.class).updateReference(resourceDb, "group", groupBinaryRepositoryEdgeRepository);

    }


    BinaryRepositoryMapper mapper = Selma.mapper(BinaryRepositoryMapper.class);

    public BinaryRepositoryDb convertResourceToResourceDb(BinaryRepository object) {
        return mapper.asBinaryRepositoryDb(object);
    }

    public BinaryRepository convertResourceDbToResource(BinaryRepositoryDb object) {
        LeanResourceDbUtils leanResourceDbUtils = new LeanResourceDbUtils();
        return mapper.asBinaryRepository((BinaryRepositoryDb) leanResourceDbUtils.leanResourceDb(object));
    }

    public Stream<BinaryRepository> convertResourceDbToResource(Stream<BinaryRepositoryDb> objectsStream){
        LeanResourceDbUtils leanUtils = new LeanResourceDbUtils();
        return objectsStream.map(i -> (BinaryRepositoryDb) leanUtils.leanResourceDb(i))
        .collect(Collectors.toList())
        .parallelStream()
        .map(i -> mapper.asBinaryRepository(i));
    }
}
