/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

package org.kathra.resourcemanager.binaryrepository.dao;

import com.arangodb.springframework.annotation.Document;
import com.arangodb.springframework.annotation.Relations;
import org.kathra.core.model.BinaryRepository;
import org.kathra.core.model.BinaryRepository.*;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDb;
import java.util.List;

import org.kathra.resourcemanager.group.dao.GroupDb;
import org.kathra.core.model.Resource.*;
import org.kathra.resourcemanager.group.dao.GroupBinaryRepositoryEdge;


/**
 * Entity class BinaryRepositoryDb implementing db resource for class BinaryRepository
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2020-02-06T20:56:07.912Z
 * @author jboubechtoula
 */
@Document("BinaryRepositories")
public class BinaryRepositoryDb extends AbstractResourceDb<BinaryRepository> {

		@Relations(edges = GroupBinaryRepositoryEdge.class, lazy = true) 
		private GroupDb group; 
		private TypeEnum type; 
		private String provider; 
		private String providerId; 
		private String url; 
		private Boolean snapshot; 


        public BinaryRepositoryDb() {
        }
        public BinaryRepositoryDb(String id) {
            super(id);
        }

		public GroupDb getGroup() { return this.group;}
		public void setGroup(GroupDb group) { this.group=group;}

		public TypeEnum getType() { return this.type;}
		public void setType(TypeEnum type) { this.type=type;}

		public String getProvider() { return this.provider;}
		public void setProvider(String provider) { this.provider=provider;}

		public String getProviderId() { return this.providerId;}
		public void setProviderId(String providerId) { this.providerId=providerId;}

		public String getUrl() { return this.url;}
		public void setUrl(String url) { this.url=url;}

		public Boolean getSnapshot() { return this.snapshot;}
		public void setSnapshot(Boolean snapshot) { this.snapshot=snapshot;}



}
