/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.binaryrepository.controller;

import org.kathra.core.model.BinaryRepository;
import org.kathra.resourcemanager.binaryrepository.service.BinaryRepositoryService;
import org.kathra.resourcemanager.resource.controller.AbstractCrudController;
import org.kathra.resourcemanager.service.BinaryRepositoriesService;
import org.springframework.beans.factory.annotation.Autowired;
import org.kathra.resourcemanager.resource.service.AbstractService;
import java.util.List;

/**
 * Abstract Controller implementing BinaryRepositoriesService
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-26T18:47:41.742Z
 * @author jboubechtoula
 */
public abstract class AbstractBinaryRepositoriesController implements AbstractCrudController<BinaryRepository>, BinaryRepositoriesService {

    @Autowired
    private BinaryRepositoryService service;

    @Override
    public BinaryRepositoryService getService() {
        return service;
    }

    public BinaryRepository addBinaryRepository(BinaryRepository object) throws Exception {
        return add(object);
    }

    public String deleteBinaryRepository(String resourceId) throws Exception {
        delete(resourceId);
        return resourceId;
    }

    public BinaryRepository getBinaryRepository(String resourceId) throws Exception {
        return get(resourceId);
    }

    public List<BinaryRepository> getBinaryRepositories() throws Exception {
        return getAll();
    }

    public BinaryRepository updateBinaryRepository(String resourceId, BinaryRepository object) throws Exception {
        return update(resourceId, object);
    }

    public BinaryRepository updateBinaryRepositoryAttributes(String resourceId, BinaryRepository object) throws Exception {
        return patch(resourceId, object);
    }
}
