/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.group.dao;

import com.arangodb.springframework.core.ArangoOperations;
import org.kathra.core.model.Group;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDao;
import org.kathra.resourcemanager.resource.utils.LeanResourceDbUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.kathra.resourcemanager.resource.utils.EdgeUtils;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import fr.xebia.extras.selma.Selma;
import java.util.stream.Stream;

import org.kathra.resourcemanager.user.dao.UserDb;
import org.kathra.resourcemanager.user.dao.UserGroupEdge;
import org.kathra.resourcemanager.user.dao.UserGroupEdgeRepository;
import org.kathra.resourcemanager.binaryrepository.dao.BinaryRepositoryDb;
import org.kathra.resourcemanager.group.dao.GroupBinaryRepositoryEdge;
import org.kathra.resourcemanager.group.dao.GroupBinaryRepositoryEdgeRepository;
import org.kathra.resourcemanager.assignation.dao.AssignationDb;
import org.kathra.resourcemanager.group.dao.GroupAssignationEdge;
import org.kathra.resourcemanager.group.dao.GroupAssignationEdgeRepository;
import org.kathra.resourcemanager.group.dao.GroupDb;
import org.kathra.resourcemanager.group.dao.GroupGroupEdge;
import org.kathra.resourcemanager.group.dao.GroupGroupEdgeRepository;


/**
 * Abtrasct dao service to manage Group using GroupDb with ArangoRepository
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2020-01-12T20:00:25.682Z
 * @author jboubechtoula
 */
public abstract class AbstractGroupDao extends AbstractResourceDao<Group, GroupDb, String> {

	@Autowired
	UserGroupEdgeRepository userGroupEdgeRepository;
	@Autowired
	GroupBinaryRepositoryEdgeRepository groupBinaryRepositoryEdgeRepository;
	@Autowired
	GroupAssignationEdgeRepository groupAssignationEdgeRepository;
	@Autowired
	GroupGroupEdgeRepository groupGroupEdgeRepository;


    public AbstractGroupDao(@Autowired GroupRepository repository, @Autowired ArangoOperations operations){
        super(repository, operations);
    }

    @PostConstruct
    public void initCollectionIfNotExist(){
        if(repository.count() == 0) {
            try {
                operations.insert(new GroupDb("init"));
                repository.deleteById("init");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
//init edge repositories 
		this.userGroupEdgeRepository.count();
		this.groupBinaryRepositoryEdgeRepository.count();
		this.groupAssignationEdgeRepository.count();
		this.groupGroupEdgeRepository.count();

    }

    @Override
    public void create(Group object, String author) throws Exception {
        super.create(object, author);
        updateReferences(object);
    }

    @Override
    public void update(Group object, String author) throws Exception {
        super.update(object, author);
        updateReferences(object);
    }
    @Override
    public void delete(Group object, String author) throws Exception {
        super.delete(object, author);
        updateReferences(object);
    }
    private void updateReferences(Group object) throws Exception {
        GroupDb resourceDb = this.convertResourceToResourceDb(object);
        EdgeUtils.of(UserGroupEdge.class).updateReference(resourceDb, "technicalUser", userGroupEdgeRepository);
        if (object.getBinaryRepositories() != null) {
            List binaryRepositoriesItemsToUpdate = object.getBinaryRepositories().parallelStream().filter(Objects::nonNull).map(i -> new BinaryRepositoryDb(i.getId())).collect(Collectors.toList());
            EdgeUtils.of(GroupBinaryRepositoryEdge.class).updateList(resourceDb, binaryRepositoriesItemsToUpdate, groupBinaryRepositoryEdgeRepository);
        }
        if (object.getMembers() != null) {
            List membersItemsToUpdate = object.getMembers().parallelStream().filter(Objects::nonNull).map(i -> new AssignationDb(i.getId())).collect(Collectors.toList());
            EdgeUtils.of(GroupAssignationEdge.class).updateList(resourceDb, membersItemsToUpdate, groupAssignationEdgeRepository);
        }
        EdgeUtils.of(GroupGroupEdge.class).updateReference(resourceDb, "parent", groupGroupEdgeRepository);

    }


    GroupMapper mapper = Selma.mapper(GroupMapper.class);

    public GroupDb convertResourceToResourceDb(Group object) {
        return mapper.asGroupDb(object);
    }

    public Group convertResourceDbToResource(GroupDb object) {
        LeanResourceDbUtils leanResourceDbUtils = new LeanResourceDbUtils();
        return mapper.asGroup((GroupDb) leanResourceDbUtils.leanResourceDb(object));
    }

    public Stream<Group> convertResourceDbToResource(Stream<GroupDb> objectsStream){
        LeanResourceDbUtils leanUtils = new LeanResourceDbUtils();
        return objectsStream.map(i -> (GroupDb) leanUtils.leanResourceDb(i))
        .collect(Collectors.toList())
        .parallelStream()
        .map(i -> mapper.asGroup(i));
    }
}
