/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.catalogentrypackage.dao;

import com.arangodb.springframework.core.ArangoOperations;
import org.kathra.core.model.CatalogEntryPackage;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDao;
import org.kathra.resourcemanager.resource.utils.LeanResourceDbUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.kathra.resourcemanager.resource.utils.EdgeUtils;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import fr.xebia.extras.selma.Selma;
import java.util.stream.Stream;

import org.kathra.resourcemanager.catalogentry.dao.CatalogEntryDb;
import org.kathra.resourcemanager.catalogentrypackage.dao.CatalogEntryPackageCatalogEntryEdge;
import org.kathra.resourcemanager.catalogentrypackage.dao.CatalogEntryPackageCatalogEntryEdgeRepository;


/**
 * Abtrasct dao service to manage CatalogEntryPackage using CatalogEntryPackageDb with ArangoRepository
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-28T17:06:24.811Z
 * @author Julien Boubechtoula
 */
public abstract class AbstractCatalogEntryPackageDao extends AbstractResourceDao<CatalogEntryPackage, CatalogEntryPackageDb, String> {

	@Autowired
	CatalogEntryPackageCatalogEntryEdgeRepository catalogEntryPackageCatalogEntryEdgeRepository;


    public AbstractCatalogEntryPackageDao(@Autowired CatalogEntryPackageRepository repository, @Autowired ArangoOperations operations){
        super(repository, operations);
    }

    @PostConstruct
    public void initCollectionIfNotExist(){
        if(repository.count() == 0) {
            try {
                operations.insert(new CatalogEntryPackageDb("init"));
                repository.deleteById("init");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
//init edge repositories 
		this.catalogEntryPackageCatalogEntryEdgeRepository.count();

    }

    @Override
    public void create(CatalogEntryPackage object, String author) throws Exception {
        super.create(object, author);
        updateReferences(object);
    }

    @Override
    public void update(CatalogEntryPackage object, String author) throws Exception {
        super.update(object, author);
        updateReferences(object);
    }
    @Override
    public void delete(CatalogEntryPackage object, String author) throws Exception {
        super.delete(object, author);
        updateReferences(object);
    }
    private void updateReferences(CatalogEntryPackage object) throws Exception {
        CatalogEntryPackageDb resourceDb = this.convertResourceToResourceDb(object);
        EdgeUtils.of(CatalogEntryPackageCatalogEntryEdge.class).updateReference(resourceDb, "catalogEntry", catalogEntryPackageCatalogEntryEdgeRepository);

    }


    CatalogEntryPackageMapper mapper = Selma.mapper(CatalogEntryPackageMapper.class);

    public CatalogEntryPackageDb convertResourceToResourceDb(CatalogEntryPackage object) {
        return mapper.asCatalogEntryPackageDb(object);
    }

    public CatalogEntryPackage convertResourceDbToResource(CatalogEntryPackageDb object) {
        LeanResourceDbUtils leanResourceDbUtils = new LeanResourceDbUtils();
        return mapper.asCatalogEntryPackage((CatalogEntryPackageDb) leanResourceDbUtils.leanResourceDb(object));
    }

    public Stream<CatalogEntryPackage> convertResourceDbToResource(Stream<CatalogEntryPackageDb> objectsStream){
        LeanResourceDbUtils leanUtils = new LeanResourceDbUtils();
        return objectsStream.map(i -> (CatalogEntryPackageDb) leanUtils.leanResourceDb(i))
        .collect(Collectors.toList())
        .parallelStream()
        .map(i -> mapper.asCatalogEntryPackage(i));
    }
}
