/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.sourcerepository.dao;

import com.arangodb.springframework.annotation.Document;
import com.arangodb.springframework.annotation.Relations;
import org.kathra.core.model.SourceRepository;
import org.kathra.core.model.SourceRepository.*;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDb;
import java.util.List;

import org.kathra.core.model.Resource.*;


/**
 * Entity class SourceRepositoryDb implementing db resource for class SourceRepository
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2019-12-28T18:27:37.995Z
 * @author Julien Boubechtoula
 */
@Document("SourceRepositories")
public class SourceRepositoryDb extends AbstractResourceDb<SourceRepository> {

		private String provider; 
		private String providerId; 
		private String path; 
		private String sshUrl; 
		private String httpUrl; 
		private String webUrl; 
		private List<String> branchs; 


        public SourceRepositoryDb() {
        }
        public SourceRepositoryDb(String id) {
            super(id);
        }

		public String getProvider() { return this.provider;}
		public void setProvider(String provider) { this.provider=provider;}

		public String getProviderId() { return this.providerId;}
		public void setProviderId(String providerId) { this.providerId=providerId;}

		public String getPath() { return this.path;}
		public void setPath(String path) { this.path=path;}

		public String getSshUrl() { return this.sshUrl;}
		public void setSshUrl(String sshUrl) { this.sshUrl=sshUrl;}

		public String getHttpUrl() { return this.httpUrl;}
		public void setHttpUrl(String httpUrl) { this.httpUrl=httpUrl;}

		public String getWebUrl() { return this.webUrl;}
		public void setWebUrl(String webUrl) { this.webUrl=webUrl;}

		public List<String> getBranchs() { return this.branchs;}
		public void setBranchs(List<String> branchs) { this.branchs=branchs;}



}
