/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

package org.kathra.resourcemanager.apiversion.service;

import org.kathra.core.model.ApiVersion;
import org.kathra.core.model.Component;
import org.kathra.resourcemanager.component.service.ComponentService;
import org.kathra.resourcemanager.resource.service.AbstractService;
import org.kathra.resourcemanager.resource.service.security.ResourceSecured;
import org.kathra.resourcemanager.resource.service.security.ResourceSecuredAction;
import org.kathra.resourcemanager.resource.service.security.Scope;
import org.kathra.resourcemanager.security.SessionService;
import org.kathra.resourcemanager.apiversion.dao.ApiVersionDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * Business service managing ApiVersion
 *
 * Auto-generated by resource-db-generator@1.0.0 at 2019-01-09T10:45:33.228Z
 * @author julien.boubechtoula
 */
@Service
public class ApiVersionService extends AbstractService<ApiVersion,String> {

    ComponentService componentService;

    public ApiVersionService(@Autowired ApiVersionDao dao, @Autowired SessionService sessionService, @Autowired ComponentService componentService) {
        super(dao, sessionService);
        this.componentService = componentService;
    }

    @Override
    @ResourceSecured(action= ResourceSecuredAction.VALID, scopes = Scope.UPDATE, clazz=Component.class, target="object/component")
    public void create(ApiVersion object) throws Exception {
        super.create(object);
    }

    @Override
    @ResourceSecured(action= ResourceSecuredAction.VALID, scopes = Scope.UPDATE, clazz=Component.class, target="object/component")
    public void delete(ApiVersion object) throws Exception {
        super.delete(object);
    }

    @Override
    @ResourceSecured(action= ResourceSecuredAction.VALID, scopes = Scope.UPDATE, clazz=Component.class, target="object/component")
    public void update(ApiVersion object) throws Exception {
        super.update(object);
    }

    @Override
    @ResourceSecured(action= ResourceSecuredAction.VALID, scopes = Scope.UPDATE, clazz=Component.class, target="object/component")
    public void patch(ApiVersion object) throws Exception {
        super.patch(object);
    }

    @Override
    @ResourceSecured(action= ResourceSecuredAction.VALID, scopes = Scope.READ, clazz=Component.class, target="output/component")
    public Optional<ApiVersion> findById(String id) throws Exception {
        return super.findById(id);
    }

    @Override
    @ResourceSecured(action= ResourceSecuredAction.FILTER, scopes = Scope.READ, clazz=Component.class, target="output/component")
    public List<ApiVersion> findAll() throws Exception {
        return super.serviceDao.findAll(findAllIdsAuthorized());
    }

    public List<String> findAllIdsAuthorized() throws Exception {
        return ((ApiVersionDao)serviceDao).findAllByComponentIds(componentService.findAllIdsAuthorized());
    }
}
