/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

package org.kathra.resourcemanager.group.controller;

import org.kathra.core.model.Group;
import org.kathra.resourcemanager.group.service.GroupService;
import org.kathra.resourcemanager.resource.controller.AbstractCrudController;
import org.kathra.resourcemanager.service.GroupsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.kathra.resourcemanager.resource.service.AbstractService;
import java.util.List;

/**
 * Abstract Controller implementing GroupsService
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2020-02-06T20:56:05.831Z
 * @author jboubechtoula
 */
public abstract class AbstractGroupsController implements AbstractCrudController<Group>, GroupsService {

    @Autowired
    private GroupService service;

    @Override
    public GroupService getService() {
        return service;
    }

    public Group addGroup(Group object) throws Exception {
        return add(object);
    }

    public String deleteGroup(String resourceId) throws Exception {
        delete(resourceId);
        return resourceId;
    }

    public Group getGroup(String resourceId) throws Exception {
        return get(resourceId);
    }

    public List<Group> getGroups() throws Exception {
        return getAll();
    }

    public Group updateGroup(String resourceId, Group object) throws Exception {
        return update(resourceId, object);
    }

    public Group updateGroupAttributes(String resourceId, Group object) throws Exception {
        return patch(resourceId, object);
    }
}
