/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

package org.kathra.resourcemanager.implementation.controller;

import org.kathra.core.model.Implementation;
import org.kathra.resourcemanager.implementation.service.ImplementationService;
import org.kathra.resourcemanager.resource.controller.AbstractCrudController;
import org.kathra.resourcemanager.service.ImplementationsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.kathra.resourcemanager.resource.service.AbstractService;
import java.util.List;

/**
 * Abstract Controller implementing ImplementationsService
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2020-02-06T20:56:15.476Z
 * @author jboubechtoula
 */
public abstract class AbstractImplementationsController implements AbstractCrudController<Implementation>, ImplementationsService {

    @Autowired
    private ImplementationService service;

    @Override
    public ImplementationService getService() {
        return service;
    }

    public Implementation addImplementation(Implementation object) throws Exception {
        return add(object);
    }

    public String deleteImplementation(String resourceId) throws Exception {
        delete(resourceId);
        return resourceId;
    }

    public Implementation getImplementation(String resourceId) throws Exception {
        return get(resourceId);
    }

    public List<Implementation> getImplementations() throws Exception {
        return getAll();
    }

    public Implementation updateImplementation(String resourceId, Implementation object) throws Exception {
        return update(resourceId, object);
    }

    public Implementation updateImplementationAttributes(String resourceId, Implementation object) throws Exception {
        return patch(resourceId, object);
    }
}
