/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.component.dao;

import com.arangodb.springframework.annotation.Edge;
import com.arangodb.springframework.annotation.From;
import com.arangodb.springframework.annotation.To;
import org.springframework.data.annotation.Id;

import org.kathra.resourcemanager.component.dao.ComponentDb;
import org.kathra.resourcemanager.apiversion.dao.ApiVersionDb;


/**
 * Edge linking Component and ApiVersion
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-28T17:06:29.702Z
 * @author Julien Boubechtoula
 */
@Edge
public class ComponentApiVersionEdge {

    @Id
    public String id;

    @From(lazy = true)
    public ComponentDb component;

    @To(lazy = true)
    public ApiVersionDb apiVersion;

    public ComponentApiVersionEdge(){

    }

    public ComponentApiVersionEdge(final ComponentDb component, final ApiVersionDb apiVersion) {
        this.apiVersion = apiVersion;
        this.component = component;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ComponentDb getComponent() {
        return component;
    }

    public void setComponent(ComponentDb component) {
        this.component = component;
    }

    public ApiVersionDb getApiVersion() {
        return apiVersion;
    }

    public void setApiVersion(ApiVersionDb apiVersion) {
        this.apiVersion = apiVersion;
    }
}
