/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package {{package}};

import com.arangodb.springframework.annotation.Edge;
import com.arangodb.springframework.annotation.From;
import com.arangodb.springframework.annotation.To;
import org.springframework.data.annotation.Id;

{{imports}}

/**
 * Edge linking {{clazzA}} and {{clazzB}}
 *
 * Auto-generated by {{generatorSignature}}
 * @author {{author}}
 */
@Edge
public class {{clazzA}}{{clazzB}}Edge {

    @Id
    public String id;

    @From(lazy = true)
    public {{clazzA}}Db {{propertyA}};

    @To(lazy = true)
    public {{clazzB}}Db {{propertyB}};

    public {{clazzA}}{{clazzB}}Edge(){

    }

    public {{clazzA}}{{clazzB}}Edge(final {{clazzA}}Db {{propertyA}}, final {{clazzB}}Db {{propertyB}}) {
        this.{{propertyB}} = {{propertyB}};
        this.{{propertyA}} = {{propertyA}};
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public {{clazzA}}Db get{{PropertyA}}() {
        return {{propertyA}};
    }

    public void set{{PropertyA}}({{clazzA}}Db {{propertyA}}) {
        this.{{propertyA}} = {{propertyA}};
    }

    public {{clazzB}}Db get{{PropertyB}}() {
        return {{propertyB}};
    }

    public void set{{PropertyB}}({{clazzB}}Db {{propertyB}}) {
        this.{{propertyB}} = {{propertyB}};
    }
}
