/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.catalogentrypackage.controller;

import org.kathra.core.model.CatalogEntryPackage;
import org.kathra.resourcemanager.catalogentrypackage.service.CatalogEntryPackageService;
import org.kathra.resourcemanager.resource.controller.AbstractCrudController;
import org.kathra.resourcemanager.service.CatalogEntryPackagesService;
import org.springframework.beans.factory.annotation.Autowired;
import org.kathra.resourcemanager.resource.service.AbstractService;
import java.util.List;

/**
 * Abstract Controller implementing CatalogEntryPackagesService
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2020-02-06T20:56:10.906Z
 * @author jboubechtoula
 */
public abstract class AbstractCatalogEntryPackagesController implements AbstractCrudController<CatalogEntryPackage>, CatalogEntryPackagesService {

    @Autowired
    private CatalogEntryPackageService service;

    @Override
    public CatalogEntryPackageService getService() {
        return service;
    }

    public CatalogEntryPackage addCatalogEntryPackage(CatalogEntryPackage object) throws Exception {
        return add(object);
    }

    public String deleteCatalogEntryPackage(String resourceId) throws Exception {
        delete(resourceId);
        return resourceId;
    }

    public CatalogEntryPackage getCatalogEntryPackage(String resourceId) throws Exception {
        return get(resourceId);
    }

    public List<CatalogEntryPackage> getCatalogEntryPackages() throws Exception {
        return getAll();
    }

    public CatalogEntryPackage updateCatalogEntryPackage(String resourceId, CatalogEntryPackage object) throws Exception {
        return update(resourceId, object);
    }

    public CatalogEntryPackage updateCatalogEntryPackageAttributes(String resourceId, CatalogEntryPackage object) throws Exception {
        return patch(resourceId, object);
    }
}
