/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.catalogentrypackage.controller;

import org.kathra.core.model.CatalogEntryPackage;
import org.kathra.resourcemanager.resource.controller.AbstractCrudController;
import org.kathra.utils.annotations.Eager;
import org.apache.camel.cdi.ContextName;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.stereotype.Component;

import javax.inject.Named;

/**
 * Controller implementing CatalogEntryPackagesService
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-26T23:49:10.417Z
 * @author Julien Boubechtoula
 */
@Component
@Named("CatalogEntryPackagesController")
@ContextName("ResourceManager")
@Eager
@ComponentScan(basePackages = {"org.kathra.resourcemanager"})
public class CatalogEntryPackagesController extends AbstractCatalogEntryPackagesController {

    public CatalogEntryPackagesController() {

    }

}
