/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.keypair.controller;

import org.kathra.core.model.KeyPair;
import org.kathra.resourcemanager.keypair.service.KeyPairService;
import org.kathra.resourcemanager.resource.controller.AbstractCrudController;
import org.kathra.resourcemanager.service.KeyPairsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.kathra.resourcemanager.resource.service.AbstractService;
import java.util.List;

/**
 * Abstract Controller implementing KeyPairsService
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2020-02-06T20:56:17.708Z
 * @author jboubechtoula
 */
public abstract class AbstractKeyPairsController implements AbstractCrudController<KeyPair>, KeyPairsService {

    @Autowired
    private KeyPairService service;

    @Override
    public KeyPairService getService() {
        return service;
    }

    public KeyPair addKeyPair(KeyPair object) throws Exception {
        return add(object);
    }

    public String deleteKeyPair(String resourceId) throws Exception {
        delete(resourceId);
        return resourceId;
    }

    public KeyPair getKeyPair(String resourceId) throws Exception {
        return get(resourceId);
    }

    public List<KeyPair> getKeyPairs() throws Exception {
        return getAll();
    }

    public KeyPair updateKeyPair(String resourceId, KeyPair object) throws Exception {
        return update(resourceId, object);
    }

    public KeyPair updateKeyPairAttributes(String resourceId, KeyPair object) throws Exception {
        return patch(resourceId, object);
    }
}
