/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.libraryapiversion.dao;

import com.arangodb.springframework.annotation.Document;
import com.arangodb.springframework.annotation.Relations;
import org.kathra.core.model.LibraryApiVersion;
import org.kathra.core.model.LibraryApiVersion.*;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDb;
import java.util.List;

import org.kathra.resourcemanager.library.dao.LibraryDb;
import org.kathra.resourcemanager.apiversion.dao.ApiVersionDb;
import org.kathra.core.model.Resource.*;
import org.kathra.resourcemanager.libraryapiversion.dao.LibraryApiVersionLibraryEdge;
import org.kathra.resourcemanager.libraryapiversion.dao.LibraryApiVersionApiVersionEdge;


/**
 * Entity class LibraryApiVersionDb implementing db resource for class LibraryApiVersion
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2019-12-28T18:27:36.396Z
 * @author Julien Boubechtoula
 */
@Document("LibraryApiVersions")
public class LibraryApiVersionDb extends AbstractResourceDb<LibraryApiVersion> {

		@Relations(edges = LibraryApiVersionLibraryEdge.class, lazy = true) 
		private LibraryDb library; 
		@Relations(edges = LibraryApiVersionApiVersionEdge.class, lazy = true) 
		private ApiVersionDb apiVersion; 
		private ApiRepositoryStatusEnum apiRepositoryStatus; 
		private PipelineStatusEnum pipelineStatus; 


        public LibraryApiVersionDb() {
        }
        public LibraryApiVersionDb(String id) {
            super(id);
        }

		public LibraryDb getLibrary() { return this.library;}
		public void setLibrary(LibraryDb library) { this.library=library;}

		public ApiVersionDb getApiVersion() { return this.apiVersion;}
		public void setApiVersion(ApiVersionDb apiVersion) { this.apiVersion=apiVersion;}

		public ApiRepositoryStatusEnum getApiRepositoryStatus() { return this.apiRepositoryStatus;}
		public void setApiRepositoryStatus(ApiRepositoryStatusEnum apiRepositoryStatus) { this.apiRepositoryStatus=apiRepositoryStatus;}

		public PipelineStatusEnum getPipelineStatus() { return this.pipelineStatus;}
		public void setPipelineStatus(PipelineStatusEnum pipelineStatus) { this.pipelineStatus=pipelineStatus;}



}
