/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.libraryapiversion.dao;

import com.arangodb.springframework.annotation.Edge;
import com.arangodb.springframework.annotation.From;
import com.arangodb.springframework.annotation.To;
import org.springframework.data.annotation.Id;

import org.kathra.resourcemanager.libraryapiversion.dao.LibraryApiVersionDb;
import org.kathra.resourcemanager.library.dao.LibraryDb;


/**
 * Edge linking LibraryApiVersion and Library
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-26T13:40:59.752Z
 * @author jboubechtoula
 */
@Edge
public class LibraryApiVersionLibraryEdge {

    @Id
    public String id;

    @From(lazy = true)
    public LibraryApiVersionDb libraryApiVersion;

    @To(lazy = true)
    public LibraryDb library;

    public LibraryApiVersionLibraryEdge(){

    }

    public LibraryApiVersionLibraryEdge(final LibraryApiVersionDb libraryApiVersion, final LibraryDb library) {
        this.library = library;
        this.libraryApiVersion = libraryApiVersion;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public LibraryApiVersionDb getLibraryApiVersion() {
        return libraryApiVersion;
    }

    public void setLibraryApiVersion(LibraryApiVersionDb libraryApiVersion) {
        this.libraryApiVersion = libraryApiVersion;
    }

    public LibraryDb getLibrary() {
        return library;
    }

    public void setLibrary(LibraryDb library) {
        this.library = library;
    }
}
