/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.catalogentry.dao;

import com.arangodb.springframework.core.ArangoOperations;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


/**
 * Dao service to manage CatalogEntry using CatalogEntryDb with ArangoRepository
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-26T23:40:38.313Z
 * @author Julien Boubechtoula
 */
@Service
public class CatalogEntryDao extends AbstractCatalogEntryDao {

    public CatalogEntryDao(@Autowired CatalogEntryRepository repository, @Autowired ArangoOperations operations){
        super(repository, operations);
    }
}
