/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.catalogentry.dao;

import com.arangodb.springframework.annotation.Document;
import com.arangodb.springframework.annotation.Relations;
import org.kathra.core.model.Asset;
import org.kathra.core.model.CatalogEntry;
import org.kathra.core.model.CatalogEntry.*;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDb;
import java.util.List;

import org.kathra.resourcemanager.catalogentrypackage.dao.CatalogEntryPackageDb;
import org.kathra.core.model.Resource.*;
import org.kathra.resourcemanager.catalogentrypackage.dao.CatalogEntryPackageCatalogEntryEdge;


/**
 * Entity class CatalogEntryDb implementing db resource for class CatalogEntry
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-26T18:47:43.584Z
 * @author jboubechtoula
 */
@Document("CatalogEntries")
public class CatalogEntryDb extends AbstractResourceDb<CatalogEntry> {

		private String description;
		private PackageTemplateEnum packageTemplate; 
		@Relations(edges = CatalogEntryPackageCatalogEntryEdge.class, lazy = true) 
		private List<CatalogEntryPackageDb> packages; 


        public CatalogEntryDb() {
        }
        public CatalogEntryDb(String id) {
            super(id);
        }

		public String getDescription() { return this.description;}
		public void setDescription(String description) { this.description=description;}

		public PackageTemplateEnum getPackageTemplate() { return this.packageTemplate;}
		public void setPackageTemplate(PackageTemplateEnum packageTemplate) { this.packageTemplate=packageTemplate;}

		public List<CatalogEntryPackageDb> getPackages() { return this.packages;}
		public void setPackages(List<CatalogEntryPackageDb> packages) { this.packages=packages;}



}
