/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.pipeline.controller;

import org.kathra.core.model.Pipeline;
import org.kathra.resourcemanager.pipeline.service.PipelineService;
import org.kathra.resourcemanager.resource.controller.AbstractCrudController;
import org.kathra.resourcemanager.service.PipelinesService;
import org.springframework.beans.factory.annotation.Autowired;
import org.kathra.resourcemanager.resource.service.AbstractService;
import java.util.List;

/**
 * Abstract Controller implementing PipelinesService
 *
 * Auto-generated by resource-db-generator@1.1.1 at 2019-04-12T13:51:01.376Z
 * @author julien.boubechtoula
 */
public abstract class AbstractPipelinesController implements AbstractCrudController<Pipeline>, PipelinesService {

    @Autowired
    private PipelineService service;

    @Override
    public PipelineService getService() {
        return service;
    }

    public Pipeline addPipeline(Pipeline object) throws Exception {
        return add(object);
    }

    public void deletePipeline(String resourceId) throws Exception {
        delete(resourceId);
    }

    public Pipeline getPipeline(String resourceId) throws Exception {
        return get(resourceId);
    }

    public List<Pipeline> getPipelines() throws Exception {
        return getAll();
    }

    public Pipeline updatePipeline(String resourceId, Pipeline object) throws Exception {
        return update(resourceId, object);
    }

    public Pipeline updatePipelineAttributes(String resourceId, Pipeline object) throws Exception {
        return patch(resourceId, object);
    }
}
