/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

package org.kathra.resourcemanager.implementationversion.dao;

import com.arangodb.springframework.annotation.Edge;
import com.arangodb.springframework.annotation.From;
import com.arangodb.springframework.annotation.To;
import org.springframework.data.annotation.Id;

import org.kathra.resourcemanager.implementationversion.dao.ImplementationVersionDb;
import org.kathra.resourcemanager.implementation.dao.ImplementationDb;


/**
 * Edge linking ImplementationVersion and Implementation
 *
 * Auto-generated by resource-db-generator@1.3.0 at 2020-02-06T20:56:16.987Z
 * @author jboubechtoula
 */
@Edge
public class ImplementationVersionImplementationEdge {

    @Id
    public String id;

    @From(lazy = true)
    public ImplementationVersionDb implementationVersion;

    @To(lazy = true)
    public ImplementationDb implementation;

    public ImplementationVersionImplementationEdge(){

    }

    public ImplementationVersionImplementationEdge(final ImplementationVersionDb implementationVersion, final ImplementationDb implementation) {
        this.implementation = implementation;
        this.implementationVersion = implementationVersion;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ImplementationVersionDb getImplementationVersion() {
        return implementationVersion;
    }

    public void setImplementationVersion(ImplementationVersionDb implementationVersion) {
        this.implementationVersion = implementationVersion;
    }

    public ImplementationDb getImplementation() {
        return implementation;
    }

    public void setImplementation(ImplementationDb implementation) {
        this.implementation = implementation;
    }
}
