/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package {{package}}.controller;

import {{coreModelPackage}}.{{clazz}};
import {{package}}.service.{{clazz}}Service;
import org.kathra.resourcemanager.resource.controller.AbstractCrudController;
import org.kathra.resourcemanager.service.{{clazzPlural}}Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.kathra.resourcemanager.resource.service.AbstractService;
import java.util.List;

/**
 * Abstract Controller implementing {{clazzPlural}}Service
 *
 * Auto-generated by {{generatorSignature}}
 * @author {{author}}
 */
public abstract class Abstract{{clazzPlural}}Controller implements AbstractCrudController<{{clazz}}>, {{clazzPlural}}Service {

    @Autowired
    private {{clazz}}Service service;

    @Override
    public {{clazz}}Service getService() {
        return service;
    }

    public {{clazz}} add{{clazz}}({{clazz}} object) throws Exception {
        return add(object);
    }

    public void delete{{clazz}}(String resourceId) throws Exception {
        delete(resourceId);
    }

    public {{clazz}} get{{clazz}}(String resourceId) throws Exception {
        return get(resourceId);
    }

    public List<{{clazz}}> get{{clazzPlural}}() throws Exception {
        return getAll();
    }

    public {{clazz}} update{{clazz}}(String resourceId, {{clazz}} object) throws Exception {
        return update(resourceId, object);
    }

    public {{clazz}} update{{clazz}}Attributes(String resourceId, {{clazz}} object) throws Exception {
        return patch(resourceId, object);
    }
}
