/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.keypair.service;

import org.kathra.core.model.KeyPair;
import org.kathra.resourcemanager.resource.service.AbstractService;
import org.kathra.resourcemanager.security.SessionService;
import org.kathra.resourcemanager.keypair.dao.KeyPairDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Business service managing KeyPair
 *
 * Auto-generated by resource-db-generator@1.0.1 at 2019-03-13T09:54:45.893Z
 * @author julien.boubechtoula
 */
@Service
public class KeyPairService extends AbstractService<KeyPair,String> {

    public KeyPairService(@Autowired KeyPairDao dao, @Autowired SessionService sessionService) {
        super(dao, sessionService);
    }
}
