/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.keypair.dao;

import com.arangodb.springframework.annotation.Document;
import com.arangodb.springframework.annotation.Relations;
import org.kathra.core.model.KeyPair;
import org.kathra.core.model.KeyPair.*;
import org.kathra.resourcemanager.resource.dao.AbstractResourceDb;
import java.util.List;

import org.kathra.resourcemanager.group.dao.GroupDb;
import org.kathra.core.model.Resource.*;
import org.kathra.resourcemanager.keypair.dao.KeyPairGroupEdge;


/**
 * Entity class KeyPairDb implementing db resource for class KeyPair
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-26T12:41:57.073Z
 * @author jboubechtoula
 */
@Document("KeyPairs")
public class KeyPairDb extends AbstractResourceDb<KeyPair> {

		private String _private; 
		private String _public; 
		@Relations(edges = KeyPairGroupEdge.class, lazy = true) 
		private GroupDb group; 


        public KeyPairDb() {
        }
        public KeyPairDb(String id) {
            super(id);
        }

		public String get_private() { return this._private;}
		public void set_private(String _private) { this._private=_private;}

		public String get_public() { return this._public;}
		public void set_public(String _public) { this._public=_public;}

		public GroupDb getGroup() { return this.group;}
		public void setGroup(GroupDb group) { this.group=group;}



}
