/* 
 * Copyright 2019 The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *
 *    IRT SystemX (https://www.kathra.org/)    
 *
 */

package org.kathra.resourcemanager.keypair.dao;

import com.arangodb.springframework.repository.ArangoRepository;
import org.springframework.stereotype.Repository;
import java.util.List;

/**
 * ArangoDb Edge Repository linking KeyPair and Group
 *
 * Auto-generated by resource-db-generator@1.2.0 at 2019-12-26T12:41:57.072Z
 * @author jboubechtoula
 */
@Repository
public interface KeyPairGroupEdgeRepository extends ArangoRepository<KeyPairGroupEdge, String> {

    public List<KeyPairGroupEdge> findAllByKeyPair(String from);
    public List<KeyPairGroupEdge> findAllByGroup(String to);
    public void deleteByKeyPair(String from);
    public void deleteByGroup(String to);
}
